### ISSUE TITLE
Ability to define metrics in dbt models

### ISSUE THREAD

**Issue by buremba** [metriql/metriql#17]
In order to use metriql in a dbt project, you need to be using [YML files](https://docs.getdbt.com/reference/declaring-properties) in dbt but not all the users are familiar with it. We should find a dbt-native way for SQL-heavy users to define them inside the SQL. One solution would be parsing column names such as `metric__[MEASURE_NAME]__[OPTIONAL_AGGREGATION_TYPE]` and creating measures automatically for these columns. 

We need to create a macro so that the users can define them as follows:

```random_model.sql
{{config(materialized='view')}}

select c_nationkey, 
    count(*) as {{measure('total_users', aggregation='sum')}}, 
    min(c_acctbal) as {{measure('min_balance', aggregation='min')}}
from {{source('tpch', 'customer')}} 
```

The model above will be compiled as:

```sql
select c_nationkey, 
  count(*) as metric__total_users__count, 
  min(c_acctbal) as metric__min_balance__min
from snowflake_sample_data.tpch_sf1.customer group by 1
```

If there is no YML file that documents the model, we will get the table schema, create dimensions for each column, look for the columns that start with `metric__`, and create a measure for each of them. The dataset will look something like this:

```
target: source('tpch', "customer")
dimensions:
  c_nationkey:
        column: c_nationkey
  total_users:
        column: total_users
  min_balance:
        column: min_balance
measures:
  total_users_sum:
     aggregation: sum
     column: total_users
  min_balance_min:
     aggregation: min
     column: min_balance
```
