### ISSUE TITLE
Relations in measures

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#61]
How to use relations in measures? I would like to do a count from a relation. I could specify the measure in that table as well if that is the way to go.

```
meta:
      metriql:
        label: Statistics
        measures:
          nr_of_meetings:
            sql: "COUNT({relation.some_relation}.id)"
        mappings:
          event_timestamp: date
        relations:
          some_relation:
            to: ref('some_relation')
            sql: "{TABLE}.id = {TARGET}.id AND {TABLE}.date = DATE({TARGET}.booked_date)"
            relationship: one_to_many
```
