### ISSUE TITLE
Metriql cannot find parent models of dbt metrics

### ISSUE THREAD

**Issue by mjirv** [metriql/metriql#82]
I have a (valid) dbt metric defined as follows:
```yaml
  - name: orders
    label: Orders
    model: ref('orders')
    description: The number of orders

    type: count

    timestamp: order_date
    time_grains: [day, week, month, quarter, year]

    dimensions:
      - status
      - customer_id
```

When running `metriql serve` I get the following error:

```
May 26, 2022 1:36:06 AM com.metriql.dbt.DbtManifestParser parse
INFO: Parsing 30 nodes, 0 sources and 4 metrics
Exception in thread "main" Unable to find `orders` metric's parent model `ref('orders')`
```

I have a model named `orders`, ran `dbt compile` just before running `metriql serve`, and confirmed the `orders` model is in my `manifest.json`.

Changing quotation styles and including the package name did not help.
