### ISSUE TITLE
Repeated Alias

### ISSUE THREAD

**Issue by edlouth** [metriql/metriql#87]
I have been following the example here https://metriql.com/tutorial/for-starters

When I run
```
curl -X POST -H "Content-Type: application/json" -d '{"type": "segmentation", "report": { "dataset": "source_metriql_tpch_customer", "dimensions": ["c_name"], "measures": ["total_rows"]}}'  http://localhost:5656/api/v0/query
```

I get the following response
```json
{
    "id": "4665b41c-b3c9-4887-bbbe-ffc69bee8e81",
    "startedAt": "2022-08-18T13:46:08.404927Z",
    "duration": 2.968608000,
    "user": "(unknown user)",
    "source": null,
    "status": "failed",
    "update": {
        "state": "FINISHED",
        "info": {
            "reportType": "segmentation",
            "query": {
                "modelName": "source_metriql_tpch_customer",
                "dimensions": [
                    {
                        "name": "c_name",
                        "modelName": "source_metriql_tpch_customer",
                        "relationName": null,
                        "postOperation": null,
                        "pivot": null
                    }
                ],
                "measures": [
                    {
                        "modelName": "source_metriql_tpch_customer",
                        "name": "total_rows",
                        "relationName": null
                    }
                ],
                "filters": null,
                "reportOptions": null,
                "defaultDateRange": null,
                "limit": null,
                "orders": null
            },
            "compiledQuery": "SELECT \n    t1.c_name AS c_name,\n    count(1) AS total_rows\nFROM snowflake_sample_data.tpch_sf1.customer AS t1 AS t1\n\n    GROUP BY\n    1 \n"
        },
        "nodes": 1,
        "percentage": null,
        "elapsedTimeMillis": null,
        "totalBytes": null,
        "processedBytes": null
    },
    "result": {
        "metadata": null,
        "result": null,
        "error": {
            "message": "SQL compilation error:\nsyntax error line 4 at position 51 unexpected 'AS'.",
            "sqlState": "42000",
            "errorCode": 1003,
            "errorLine": null,
            "charPositionInLine": null
        },
        "properties": {
            "limit": 1000,
            "query": "SELECT \n    t1.c_name AS c_name,\n    count(1) AS total_rows\nFROM snowflake_sample_data.tpch_sf1.customer AS t1 AS t1\n\n    GROUP BY\n    1 \n"
        },
        "responseHeaders": null
    }
}
```

which has two `AS t1`, hence it show a compliation error.

My `schema.yml` looks like this
```yml
version: 2
sources:
  - name: tpch
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        meta:
          metriql:
            measures:
              total_rows:
                aggregation: count
        columns:
          - name: c_name
            meta:
              metriql.dimension:
                type: string
```
