### ISSUE TITLE
Looker Integration

### ISSUE THREAD

**Issue by emresemercioglu** [metriql/metriql#9]

**Comment by jpau** [comment]
Thanks Emre! This would be great.

I wonder what the development workflow would look like. For example -- would the CLI generate `view` files only, or might it stub `model` files too? And after the initial creation, on further iterations, would the CLI track the LookML-specific parts that get updated? Or might the onus be on the user -- at least at the start -- to track those manually?

**Comment by buremba** [comment]
Hey @jpau , we will be generating `view` files a structure everything under a `model`. There is a similar project here as well:
https://github.com/lightdash/dbt2looker (See https://github.com/lightdash/dbt2looker/blob/main/example/lookml/hubble_analytics.model)

For the LookML specific attributes, you will be able to configure the fields as follows:

```yml
columns:
  - name: col
    meta:
      metriql.dimension:
         report:
            looker:
              type: distance
```

The `report.looker` spec will be identical to LookML dimension: https://docs.looker.com/reference/field-reference/dimension-type-reference
