### ISSUE TITLE
how to use pivots propertie?

### ISSUE THREAD

**Issue by lialzm** [metriql/metriql#92]
Hi teams

have some example about pivots?

I use pivot like below

```
      metriql:
        measures:
          count:
            aggregation: count
        dimensions:
          sex:
            column: sex
            pivot: true
          email:
            column: email
            pivot: true
```

but it can't work,when request rest api

```
curl --location --request POST '127.0.0.1:5656/api/v0/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "segmentation",
    "report": {
        "dataset": "model_db_user",
        "dimensions": [
            {
                "name": "email"
            },
            {
                "name": "sex"
            }
        ],
        "measures": [
            "count"
        ],
        "limit": 10,
        "reportOptions": {}
    }
}'
```
